/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-10-04 13:13:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.*;
import java.util.*;

public final class partnumbermasterform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/Program%20Files/eclipse/workspace/dailyMoldingWorkG_tomcat/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1308094570000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1709434660000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	List<Partnumbermaster> list=(List<Partnumbermaster>)request.getAttribute("list");
    Partnumbermaster partnumbermaster=(Partnumbermaster)request.getAttribute("partnumbermaster");
	
	String id=partnumbermaster==null ? "":String.valueOf(partnumbermaster.getId());
	String partnumber=partnumbermaster == null ? "":String.valueOf(partnumbermaster.getPartnumber());
    String sparepartnumber1=partnumbermaster == null ? "":String.valueOf(partnumbermaster.getSparepartnumber1());
    String sparepartnumber2=partnumbermaster == null ? "":String.valueOf(partnumbermaster.getSparepartnumber2());
    String sparepartnumber3=partnumbermaster == null ? "":String.valueOf(partnumbermaster.getSparepartnumber3());

	String err=(String)request.getAttribute("err");
	String msg=(String)request.getAttribute("msg");
	String arrangementLabel=(String)request.getAttribute("arrangementLabel");
	
	// セッションスコープからユーザー情報を取得
	User loginUser = (User) session.getAttribute("loginUser");

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ja\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("<!-- Bootstrap CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css\" integrity=\"sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M\" crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/Partnumbermasterform.css\">\n");
      out.write("<title>DailyMoldingWorkG</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
 if(err !=null){
      out.write("\n");
      out.write("<div class=\"alert alert-danger\" role=\"alert\">\n");
      out.print(err );
      out.write("\n");
      out.write("</div>\n");
} 
      out.write('\n');
 if(msg !=null){
      out.write("\n");
      out.write("<div class=\"alert alert-success\" role=\"alert\">\n");
      out.print(msg );
      out.write("\n");
      out.write("</div>\n");
} 
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container-fluid\" style=\"margin-top:20px;\">\n");
      out.write("\n");
      out.write("<form action=\"");
      out.print( request.getContextPath() );
      out.write("/PartnumbermasterForm\" method=\"post\" >\n");
      out.write("\n");
      out.write("<header>\n");
      out.write("	<ul> \n");
      out.write("	    <!-- loginUser分岐処理 -->\n");
      out.write("    	<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main\">SingleData</a></li>\n");
      out.write("    	");
 if(loginUser != null) {
      out.write("\n");
      out.write("    	<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/Ingestiondata\">Log</a></li>\n");
      out.write("    	<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/PartnumbermasterForm\">PartnumbermasterForm</a></li>\n");
      out.write("    	<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/PartnumbermasterList\">PartnumbermasterList</a></li>\n");
      out.write("    	<li class=\"contact\">");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write(":ログイン中</li>\n");
      out.write("    	");
 } else { 
      out.write("\n");
      out.write("    	<li class=\"contact\">");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write(":ログイン中</li>\n");
      out.write("    	");
 } 
      out.write("\n");
      out.write("	</ul>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<div class=\"form-row\">\n");
      out.write("  <div class=\"form-group col-sm-6\">\n");
      out.write("    <label for=\"partnumber\" class=\"required-label\" id=\"partnumber_label\"><b>品番:</b></label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"partnumber\" name=\"partnumber\" value=\"");
      out.print(partnumber);
      out.write("\" placeholder=\"品番を入力してください\">\n");
      out.write(" </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"form-row\">\n");
      out.write("  <div class=\"form-group col-sm-6\">\n");
      out.write("    <label for=\"sparepartnumber1\" class=\"\" id=\"sparepartnumber1_label\"><b>予備品番1:</b></label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"sparepartnumber1\" name=\"sparepartnumber1\" value=\"");
      out.print(sparepartnumber1);
      out.write("\" placeholder=\"予備品番1を入力してください\">\n");
      out.write(" </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"form-row\">\n");
      out.write("  <div class=\"form-group col-sm-6\">\n");
      out.write("    <label for=\"sparepartnumber2\" class=\"\" id=\"sparepartnumber2_label\"><b>予備品番2:</b></label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"sparepartnumber2\" name=\"sparepartnumber2\" value=\"");
      out.print(sparepartnumber2);
      out.write("\" placeholder=\"予備品番2を入力してください\">\n");
      out.write(" </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"form-row\">\n");
      out.write("  <div class=\"form-group col-sm-6\">\n");
      out.write("    <label for=\"sparepartnumber3\" class=\"\" id=\"sparepartnumber3_label\"><b>予備品番3:</b></label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"sparepartnumber3\" name=\"sparepartnumber3\" value=\"");
      out.print(sparepartnumber3);
      out.write("\" placeholder=\"予備品番3を入力してください\">\n");
      out.write(" </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
if(!id.isEmpty()) {
      out.write("\n");
      out.write("<input type=\"hidden\" name=\"id\" value=\"");
      out.print(id );
      out.write('"');
      out.write('>');
      out.write('\n');
} 
      out.write("\n");
      out.write("\n");
      out.write("<button type=\"submit\" class=\"btn btn-primary custom-btn\" id=\"registration\" style=\"margin-left: 15px;\" onclick=\"submitForm()\">");
      out.print(id.isEmpty()?"登録":"更新" );
      out.write("</button>\n");
      out.write(" \n");
      out.write("<footer>\n");
      out.write("	<ul>\n");
      out.write("    	<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/Logout\">Logout</a></li>\n");
      out.write("    </ul>\n");
      out.write("	\n");
      out.write("</footer>\n");
      out.write(" \n");
      out.write("</form>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("const forms=document.getElementsByClassName(\"form-control\");\n");
      out.write("const alerts=document.getElementsByClassName(\"alert\");\n");
      out.write("for(let i=0;i<forms.length;i++){\n");
      out.write("	forms[i].addEventListener(\"focus\",()=>{\n");
      out.write("		for(let j=0;j<alerts.length;j++){\n");
      out.write("			alerts[j].style.display=\"none\";\n");
      out.write("		}\n");
      out.write("	});\n");
      out.write("}\n");
      out.write("//イベントリスナーを追加\n");
      out.write("document.getElementById('partnumber').addEventListener('change', function () {\n");
      out.write("    preventDuplicate(this);\n");
      out.write("});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/view/partnumbermasterform.jsp(57,25) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/view/partnumbermasterform.jsp(59,25) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue("localuser");
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
